
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todotask?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true